name: portfolio
description: Nahaliel's Portfolio
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  google_fonts: ^4.0.3
  lottie: ^2.2.0
  model_viewer_plus: ^1.5.0
  animated_text_kit: ^4.2.2
  line_icons: ^2.0.1
  animated_background: ^2.0.0
  url_launcher: ^6.1.10
  responsive_framework: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true 
  assets:
    - assets/
    - assets/animations/
    - assets/documents/
    - assets/documents/Curriculum-Nahaliel.pdf
    - assets/images/
    - assets/images/light.png
    - assets/objects/
    - assets/objects/profile.gltf
    
