name: Flutter Web CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get Repository
      uses: actions/checkout@v3
      
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.6'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build web app
      run: flutter build web


    - name: Setup GitHub Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build/web
      
    - name: Deploy to GitHub Pages
      id: deplyment
      uses: actions/deploy-pages@v1
