# Workflow to build and deploy a Flutter Web app to Github Pages
name: Deploy Flutter Web to Github Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # build job
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get Repository
      uses: actions/checkout@v3
      
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
        
    - name: Install dependencies
      run: flutter pub get

    - name: Create env file
      run: |
        echo "API_KEY=${{secrets.API_KEY}}" >> $GITHUB_WORKSPACE/portfolio/.env
        echo "APP_ID=${{secrets.APP_ID}}" >> $GITHUB_WORKSPACE/portfolio/.env
        echo "MESSAGING_SENDER_ID=${{secrets.MESSAGING_SENDER_ID}}" >> $GITHUB_WORKSPACE/portfolio/.env
        echo "PROJECT_ID=${{secrets.PROJECT_ID}}" >> $GITHUB_WORKSPACE/portfolio/.env
        echo "AUTH_DOMAIN=${{secrets.AUTH_DOMAIN}}" >> $GITHUB_WORKSPACE/portfolio/.env
        echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> $GITHUB_WORKSPACE/portfolio/.env
        echo "STORAGE_BUCKET=${{secrets.STORAGE_BUCKET}}" >> $GITHUB_WORKSPACE/portfolio/.env
        echo "MEASUREMENT_ID=${{secrets.MEASUREMENT_ID}}" >> $GITHUB_WORKSPACE/portfolio/.env
      working-directory: $GITHUB_WORKSPACE
      
    - name: Build web app
      run: flutter build web --web-renderer canvaskit --release

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build/web
      
  # deploy job  
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
