# Workflow to build and deploy a Flutter Web app to Github Pages
name: Deploy Flutter Web to Github Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # build job
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get Repository
      uses: actions/checkout@v3
      
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.6'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build web app
      run: flutter build web --web-renderer html --release --base-href="/portfolio/"

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build/web
      
  # deploy job  
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
