# Workflow to build and deploy a Flutter Web app to Github Pages
name: Deploy Flutter Web to Github Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # build job
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get Repository
      uses: actions/checkout@v3
      
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
        
    - name: Install dependencies
      run: flutter pub get

    - name: Create env file
      uses: SpicyPizza/create-envfile@v1.3
      with:
        file_name: .env
        fail_on_empty: false

    - name: Getting secrets
      run: |
        sudo chown $USER:$USER ${{github.workspace}}/.env
        echo "API_KEY=${{secrets.API_KEY}}" >> ${{github.workspace}}/.env
        echo "APP_ID=${{secrets.APP_ID}}" >> ${{github.workspace}}/.env
        echo "MESSAGING_SENDER_ID=${{secrets.MESSAGING_SENDER_ID}}" >> ${{github.workspace}}/.env
        echo "PROJECT_ID=${{secrets.PROJECT_ID}}" >> ${{github.workspace}}/.env
        echo "AUTH_DOMAIN=${{secrets.AUTH_DOMAIN}}" >> ${{github.workspace}}/.env
        echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> ${{github.workspace}}/.env
        echo "STORAGE_BUCKET=${{secrets.STORAGE_BUCKET}}" >> ${{github.workspace}}/.env
        echo "MEASUREMENT_ID=${{secrets.MEASUREMENT_ID}}" >> ${{github.workspace}}/.env
        echo ls ${{github.workspace}}
      
    - name: Build web app
      run: flutter build web --web-renderer canvaskit --release

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build/web
      
  # deploy job  
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
