# Workflow to build and deploy a Flutter Web app to Github Pages
name: Deploy Flutter Web to Github Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # build job
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get Repository
      uses: actions/checkout@v3
      
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
        
    - name: Install dependencies
      run: flutter pub get

    - name: Create env file
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_API_KEY: ${{ vars.API_KEY }}
        envkey_APP_ID: ${{ vars.APP_ID }}
        envkey_MESSAGING_SENDER_ID: ${{ vars.MESSAGING_SENDER_ID }}
        envkey_PROJECT_ID: ${{ vars.PROJECT_ID }}
        envkey_AUTH_DOMAIN: ${{ vars.AUTH_DOMAIN }}
        envkey_STORAGE_BUCKET: ${{ vars.STORAGE_BUCKET }}
        envkey_MEASUREMENT_ID: ${{ vars.MEASUREMENT_ID }}
        directory: portfolio
        file_name: .env
        fail_on_empty: true
      
    - name: Build web app
      run: flutter build web --web-renderer canvaskit --release

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build/web
      
  # deploy job  
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
